server:
  port: 8080
spring:
  # 可选（引入jpa时可以防止初始化冲突，酌情配置）
#  jpa:
#    hibernate:
#      ddl-auto: none # 关闭 Hibernate 的自动建表功能，避免与 schema.sql 冲突
  sql:
    init:
#      mode: embedded # 嵌入式数据库时才执行初始化脚本 (h2磁盘模式不认为是嵌入式数据库，不会初始化)
      mode: always # 启动始终执行
      schema-locations: classpath:schema.sql # 用于执行表结构初始化，默认为：classpath:schema.sql，也可以自定义路径
#      data-locations: classpath:data.sql # 数据初始化 sql，默认为：classpath:data.sql，也可以自定义路径
  h2:
    console:
      enabled: true
      path: /h2-console # h2 控制台地址
  datasource:
    # 磁盘模式，保存路径在jar同级的data目录
#    url: jdbc:h2:file:./springboot-h2/data/myh2db;
    # 内存模式
    url: jdbc:h2:mem:test-db
    driver-class-name: org.h2.Driver
    username: admin
    password: 123456



